#!/usr/bin/env bash
#-exclude-classes net.guttershark.StartHere \
ME=`whoami`
ASDOC="/Users/${ME}/dev/flex3sdk/bin/"
AS_PATH="/Users/${ME}/dev/codelibs/as/"

rm -rf ./docs/*
${ASDOC}asdoc \
-source-path ./lib/as/ \
-source-path ${AS_PATH}/externals/ \
-source-path "/Applications/Adobe CS3/Adobe Flash CS3/Configuration/Component Source/ActionScript 3.0/User Interface" \
-source-path "/Applications/Adobe CS3/Adobe Flash CS3/Configuration/Component Source/ActionScript 3.0/FLVPlayback" \
-source-path "/Applications/Adobe CS3/Adobe Flash CS3/Configuration/ActionScript 3.0/Classes"  \
-doc-sources ./lib/as/net/guttershark/ \
-main-title "Guttershark Flash API Docs" \
-window-title "Guttershark Flash API Docs" \
-output ./docs/ \
-exclude-classes com.asual.swfaddress.SWFAddress \
-exclude-classes com.asual.swfaddress.SWFAddressEvent \
-exclude-classes net.guttershark.display.controls.tree.Tree \
-exclude-classes net.guttershark.display.controls.tree.TreeEvent \
-exclude-classes net.guttershark.display.controls.tree.TreeNode \
-exclude-classes net.guttershark.display.controls.tree.TreeNodeRenderer \
-exclude-classes net.guttershark.display.controls.tree.TreeNodeStates \
-exclude-classes net.guttershark.display.controls.tree.TreeNodeTypes \
-exclude-classes net.guttershark.display.controls.scrolling.VerticalScroller \
-exclude-classes net.guttershark.display.video.FLV \
-exclude-classes net.guttershark.display.video.FLVPlayer \
-exclude-classes net.guttershark.display.renderers.BitmapRenderer \
-exclude-classes net.guttershark.display.renderers.FLVRenderer \
-exclude-classes fl.events.ColorPickerEvent \
-exclude-classes fl.events.ComponentEvent \
-exclude-classes fl.events.DataChangeEvent \
-exclude-classes fl.events.DataChangeType \
-exclude-classes fl.events.DataGridEvent \
-exclude-classes fl.events.DataGridEventReason \
-exclude-classes fl.events.ListEvent \
-exclude-classes fl.motion.easing.Quadratic \
-exclude-classes fl.data.DataProvider \
-exclude-classes fl.data.SimpleCollectionItem \
-exclude-classes fl.core.InvalidationType \
-exclude-classes fl.core.UIComponent \
-exclude-classes fl.containers.BaseScrollPane \
-exclude-classes fl.controls.dataGridClasses.DataGridCellRenderer \
-exclude-classes fl.controls.dataGridClasses.DataGridColumn \
-exclude-classes fl.controls.dataGridClasses.HeaderRenderer \
-exclude-classes fl.controls.dataGridClasses.DataGridCellEditor \
-exclude-classes fl.controls.listClasses.ListData \
-exclude-classes fl.controls.listClasses.CellRenderer \
-exclude-classes fl.controls.listClasses.ICellRenderer \
-exclude-classes fl.controls.BaseButton \
-exclude-classes fl.controls.Button \
-exclude-classes fl.controls.ButtonLabelPlacement \
-exclude-classes fl.controls.ColorPicker \
-exclude-classes fl.controls.ComboBox \
-exclude-classes fl.controls.DataGrid \
-exclude-classes fl.controls.LabelButton \
-exclude-classes fl.controls.List \
-exclude-classes fl.controls.ScrollBar \
-exclude-classes fl.controls.ScrollBarDirection \
-exclude-classes fl.controls.ScrollPolicy \
-exclude-classes fl.controls.SelectableList \
-exclude-classes fl.controls.TextInput \
-exclude-classes fl.managers.IFocusManager \
-exclude-classes fl.managers.IFocusManagerGroup \
-exclude-classes fl.managers.IFocusManagerComponent \
-exclude-classes fl.managers.FocusManager \
-exclude-classes fl.managers.StyleManager \
-exclude-classes com.pixelbreaker.ui.osx.MacMouseWheel \
-exclude-classes gs.TweenMax \
-exclude-classes gs.TweenLite \
-exclude-classes gs.TweenFilterLite \
-exclude-classes fl.events.ScrollEvent \
-exclude-classes fl.video.INCManager \
-exclude-classes fl.video.IVPEvent \
-exclude-classes fl.video.AutoLayoutEvent \
-exclude-classes fl.video.CuePointEvent \
-exclude-classes fl.video.CuePointType \
-exclude-classes fl.video.FLVPlayback \
-exclude-classes fl.video.LayoutEvent \
-exclude-classes fl.video.MetadataEvent \
-exclude-classes fl.video.NCManager \
-exclude-classes fl.video.SkinErrorEvent \
-exclude-classes fl.video.SoundEvent \
-exclude-classes fl.video.VideoAlign \
-exclude-classes fl.video.VideoError \
-exclude-classes fl.video.VideoEvent \
-exclude-classes fl.video.VideoPlayer \
-exclude-classes fl.video.VideoProgressEvent \
-exclude-classes fl.video.VideoScaleMode \
-exclude-classes fl.video.VideoState \
-left-frameset-width 350 \
-package net.guttershark "The net.guttershark package contains all Actionscript 3 classes, namespaces, and meta data for the net.guttershark package." \
-package net.guttershark.control "The net.guttershark.control package contains classes for working with Flash sites and Document classes." \
-package net.guttershark.display "The net.guttershark.ui package contains classes and packages that are for working with user interface controls." \
-package net.guttershark.display.controls "The net.guttershark.ui.controls package contains base classes for generic user interface elements." \
-package net.guttershark.display.controls.buttons "The net.guttershark.ui.controls.buttons package contains base classes for generic button user interface elements." \
-package net.guttershark.display.controls.scrolling "The net.guttershark.ui.controls.scrolling package contains base classes for generic scrolling elements." \
-package net.guttershark.display.views "The net.guttershark.ui.controls.views package contains base classes for generic views." \
-package net.guttershark.display.lang "The net.guttershark.lang package contains classes used for localizing content." \
-package net.guttershark.display.video "The net.guttershark.video package contains classes use for video implementations." \
-package net.guttershark.managers "The net.guttershark.managers package contains classes for managing player wide functionality." \
-package net.guttershark.model "The net.guttershark.model package contains classes for working with model classes and site xml files." \
-package net.guttershark.support.preloading "The net.guttershark.preloading package contains classes for preloading assets." \
-package net.guttershark.support.preloading.events "The net.guttershark.preloading.events package contains event classes used within the preloading package." \
-package net.guttershark.support.preloading.workers "The net.guttershark.preloading.worker package contains worker classes that implement loading of different types of assets. These classes are base classes used with a PreloadingController." \
-package net.guttershark.support.servicemanager.remoting "The net.guttershark.service.remoting package contains classes for working with Flash Remoting." \
-package net.guttershark.support.servicemanager.remoting.events "The net.guttershark.service.remoting.events package contains event classes used throughout the remoting package." \
-package net.guttershark.support.servicemanager.remoting.errors "The net.guttershark.service.remoting.errors package contains error classes used throughout the remoting package." \
-package net.guttershark.support.servicemanager.remoting.limiting "The net.guttershark.service.remoting.limiting package contains classes that implement limiting logic for remoting service calls." \
-package net.guttershark.support.servicemanager.remoting.paging "The net.guttershark.service.remoting.paging package contains classes for implementing paging with a remoting service." \
-package net.guttershark.util "The net.guttershark.util package contains utility classes, such as AutoSuggest." \
-package net.guttershark.util.akamai "The net.guttershark.akamai package contains classes for Akamai services." \
-package net.guttershark.util.autosuggest "The net.guttershark.util.autosuggest package contains classes that implement an auto suggest." \
-package net.guttershark.util.cache "The net.guttershark.util.cache package contains classes that implement caching of objects into cache stores." \