package{	import flash.display.MovieClip;
	import flash.text.TextField;
	import flash.utils.setTimeout;
	
	import fl.controls.Button;
	
	import gs.TweenMax;
	import gs.easing.Quad;
	
	import net.guttershark.control.DocumentController;
	import net.guttershark.control.PreloadController;
	import net.guttershark.display.FLV;
	import net.guttershark.support.events.FLVEvent;
	import net.guttershark.support.preloading.Asset;
	import net.guttershark.support.preloading.events.PreloadProgressEvent;	
	public class Main extends DocumentController	{				private var flv:FLV;		public var playb:Button;		public var pauseb:Button;		public var resume:Button;		public var bar:MovieClip;		public var seekToPercent:Button;		public var seekToPx:Button;		public var stopb:Button;		public var buffer:MovieClip;		public var play1:Button;		public var play2:Button;		public var pbar:MovieClip;		public var prelabel:TextField;		private var tto:Function;		public function Main()		{			super();		}				override protected function setupComplete():void		{			tto = TweenMax.to;			stage.scaleMode = "noScale";			flv = new FLV();			flv.traceStatuses = true;			addChild(flv.video);			em.handleEvents(playb,this,"onPlay");			em.handleEvents(pauseb,this,"onPause");			em.handleEvents(resume,this,"onResume");			em.handleEvents(seekToPx,this,"onPX");			em.handleEvents(seekToPercent,this,"onPC");			em.handleEvents(stopb,this,"onStop");			em.handleEvents(play1,this,"onPlay1");			em.handleEvents(play2,this,"onPlay2");			em.handleEvents(flv,this,"onFLV");			pc = new PreloadController(349);			pc.addItems([new Asset("gears_madworld.flv","madworld"),new Asset("adidas_carry.flv","adidas")]);			em.handleEvents(pc,this,"onPRL");			pc.start();		}				public function onPRLProgress(ppe:PreloadProgressEvent):void		{			if(pbar.width == ppe.pixels) return;			tto(pbar,.3,{width:ppe.pixels,ease:Quad.easeIn,overwrite:true});			if(ppe.percent>=100) setTimeout(hidePreload,300);		}				public function onPRLComplete():void		{			onPlay1Click();		}				private function hidePreload():void		{			TweenMax.sequence(pbar,[{time:.2,tint:0xFF0066},{delay:.2,time:.1,autoAlpha:0}]);			tto(prelabel,.3,{delay:.4,autoAlpha:0});		}		public function onPlay1Click():void		{			flv.load("gears_madworld.flv",320,240,4,true);		}				public function onPlay2Click():void		{			flv.load("adidas_carry.flv",320,240,4,true);		}				public function onFLVMeta(fe:FLVEvent):void		{			//trace("META DATA");			//trace(fe.metadata);		}				public function onFLVProgress(fe:FLVEvent):void		{			//trace("PROGRESS","[%LOADED: "+fe.percentLoaded,"] [%BUFFERED: "+fe.percentBuffered,"] [PXPLAYED: "+fe.pixelsPlayed,"] [PXBUFFERED: "+fe.pixelsBuffered+"]");			bar.width = fe.pixelsPlayed;			buffer.width = fe.pixelsBuffered;		}				public function onFLVBufferFull():void		{			flv.resume();		}				public function onFLVBufferEmpty():void		{			flv.pause();		}		public function onFLVStop():void		{			trace("stopped");		}		public function onFLVStart():void		{			trace("started");		}				public function onFLVStreamNotFound(fe:FLVEvent):void		{			trace("not found",fe.url);		}		public function onFLVSeekNotify():void		{			trace("seeked");		}		
		public function onStopClick():void		{			flv.stop();		}				public function onPCClick():void		{			flv.seekToPercent(50);		}				public function onPXClick():void		{			flv.seekToPixel(40);		}		public function onPlayClick():void		{			flv.play();		}				public function onPauseClick():void		{			flv.pause();		}				public function onResumeClick():void		{			flv.resume();		}	}}